# Generated by Django 4.2.27 on 2026-01-04 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_no', models.CharField(max_length=50)),
                ('item_price', models.IntegerField()),
                ('delivery_date', models.CharField(max_length=50)),
            ],
        ),
    ]
