# Generated by Django 4.2.27 on 2026-01-04 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
