# Generated by Django 4.2.27 on 2026-01-06 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_item_item_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='delivery_date',
        ),
    ]
