# Generated by Django 4.2.27 on 2026-01-07 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_item_delivery_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
