# Generated by Django 4.2.27 on 2026-01-13 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_item_item_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=50)),
                ('item_no', models.CharField(max_length=50)),
                ('item_price', models.IntegerField()),
                ('provisional_order', models.BooleanField(default=False)),
            ],
        ),
    ]
