# Generated by Django 4.2.27 on 2026-01-14 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_no',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
