# Generated by Django 4.2.27 on 2026-01-16 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_order_order_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='item_price',
            new_name='order_price',
        ),
    ]
