# Generated by Django 4.2.27 on 2026-01-17 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_rename_item_price_order_order_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping_date', models.DateField()),
                ('item_no', models.CharField(max_length=50)),
                ('item_name', models.CharField(max_length=50)),
                ('order_no', models.CharField(max_length=50)),
                ('unit_price', models.IntegerField()),
                ('shipping_quantity', models.IntegerField()),
            ],
        ),
    ]
